// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRq9ZPRlsvlkVBuPP6e9nAUoQeQuszEc',
    appId: '1:680148460782:web:dfbc5379edc53eb9b5bfff',
    messagingSenderId: '680148460782',
    projectId: 'ecommerce-3e245',
    authDomain: 'ecommerce-3e245.firebaseapp.com',
    storageBucket: 'ecommerce-3e245.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpLVH8xfOA23LdwXExBFOJQ6DuRhwVHM',
    appId: '1:680148460782:android:191338b5ace84ab4b5bfff',
    messagingSenderId: '680148460782',
    projectId: 'ecommerce-3e245',
    storageBucket: 'ecommerce-3e245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe1WBsdIJI7pRkVCRa1IssToP2_DJAaOs',
    appId: '1:680148460782:ios:56c20a3921bab473b5bfff',
    messagingSenderId: '680148460782',
    projectId: 'ecommerce-3e245',
    storageBucket: 'ecommerce-3e245.firebasestorage.app',
    iosBundleId: 'com.example.onlineStoreTk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDRq9ZPRlsvlkVBuPP6e9nAUoQeQuszEc',
    appId: '1:680148460782:web:967ce9d0086b56deb5bfff',
    messagingSenderId: '680148460782',
    projectId: 'ecommerce-3e245',
    authDomain: 'ecommerce-3e245.firebaseapp.com',
    storageBucket: 'ecommerce-3e245.firebasestorage.app',
  );

}